# Piotr Drąg <piotrdrag@gmail.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2011-12-21 12:18+0100\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2016-09-18 08:16-0400\n"
"Last-Translator: Piotr Drąg <piotrdrag@gmail.com>\n"
"Language-Team: Polish\n"
"Language: pl\n"
"X-Generator: Zanata 3.9.6\n"
"Plural-Forms: nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 "
"|| n%100>=20) ? 1 : 2)\n"

#: ../server/rhnPackage.py:45 ../server/rhnPackage.py:80
#: ../server/rhnPackage.py:99 ../server/rhnPackage.py:181
#: ../server/rhnPackage.py:205 ../server/rhnPackage.py:287
#, python-format
msgid "Invalid RPM package %s requested"
msgstr "Zażądano nieprawidłowego pakietu RPM %s"

#: ../server/rhnPackage.py:104 ../server/rhnPackage.py:293
msgid "Package not found"
msgstr "Nie odnaleziono pakietu"

#: ../server/apacheAuth.py:58
#, python-format
msgid "incomplete proxy authentication token: %s"
msgstr "niepełny token uwierzytelnienia pośrednika: %s"

#: ../server/apacheAuth.py:74
#, python-format
msgid "Sent proxy signature %s does not match ours %s."
msgstr "Wysłany podpis pośrednika %s nie zgadza się z naszym %s."

#: ../server/apacheAuth.py:105
msgid "declined proxy authentication"
msgstr "odmówiono uwierzytelnienia pośrednika"

#: ../server/apacheRequest.py:50
#, python-format
msgid "Invalid request received (%s)."
msgstr "Otrzymano nieprawidłowe żądanie (%s)."

#: ../server/apacheRequest.py:107
#, python-format
msgid "IMPORTANT MESSAGE FOLLOWS:\n"
"%s"
msgstr "WAŻNY KOMUNIKAT:\n"
"%s"

#: ../server/apacheRequest.py:132
#, python-format
msgid "While running '%s': caught\n"
"%s : %s\n"
msgstr "Podczas wykonywania „%s”: przechwycono\n"
"%s: %s\n"

#: ../server/apacheRequest.py:558
#, python-format
msgid "Invalid URI %s"
msgstr "Nieprawidłowy adres URI %s"

#: ../server/rhnServer/server_token.py:80
#, python-format
msgid "Token `%s' has more than one base channel assigned"
msgstr "Token „%s” ma przydzielony więcej niż jeden kanał podstawowy"

#: ../server/rhnServer/server_token.py:82
msgid "Conflicting base channels"
msgstr "Sprzeczne kanały podstawowe"

#: ../server/rhnServer/server_token.py:206
#, python-format
msgid "Failed to add server to group %s"
msgstr "Dodanie serwera do grupy %s się nie powiodło"

#: ../server/rhnServer/server_token.py:513
#, python-format
msgid "Maximum usage count of %s reached"
msgstr "Osiągnięto maksymalne użycie %s"

#: ../server/rhnServer/server_token.py:645
#, python-format
msgid "Registration failed: RHN Software service entitlements exhausted: %s"
msgstr ""
"Rejestracja się nie powiodła: wyczerpano ważności usług oprogramowania RHN: "
"%s"

#: ../server/rhnServer/server_token.py:761
msgid ""
"Stacking of re-registration tokens with different base entitlements is not "
"supported"
msgstr ""
"Nakładanie tokenów ponownej rejestracji na stos z różnymi podstawowymi "
"ważnościami jest nieobsługiwane"

#: ../server/rhnServer/server_token.py:839
#, python-format
msgid "Could not find token '%s'"
msgstr "Nie można odnaleźć tokenu „%s”"

#. Cannot use activation keys from different orgs
#: ../server/rhnServer/server_token.py:871
msgid "Tokens from mismatching orgs"
msgstr "Tokeny z niepasujących organizacji"

#. Two tokens with different kickstart sessions
#: ../server/rhnServer/server_token.py:881
msgid "Kickstart session mismatch"
msgstr "Niepasująca sesja kickstart"

#: ../server/rhnServer/server_token.py:901
msgid "Stacking of re-registration tokens is not supported"
msgstr "Nakładanie tokenów ponownej rejestracji na stos jest nieobsługiwane"

#: ../server/rhnServer/server_class.py:95
#, python-format
msgid "Architecture `%s' is not supported"
msgstr "Architektura „%s” jest nieobsługiwana"

#: ../server/rhnUser.py:383 ../server/rhnUser.py:386
msgid "Invalid username/password combination"
msgstr "Nieprawidłowe połączenie nazwy użytkownika i hasła"

#. nope, not reserved either
#: ../server/rhnUser.py:539
#, python-format
msgid "Username `%s' has not been reserved"
msgstr "Nazwa użytkownika „%s” nie została zastrzeżona"

#. New accounts have to specify an e-mail address
#: ../server/rhnUser.py:545
msgid "E-mail address not specified"
msgstr "Nie podano adresu e-mail"

#. wrong organization
#. Invalid org password
#: ../server/rhnUser.py:600 ../server/rhnUser.py:604
msgid "Invalid Organization Credentials"
msgstr "Nieprawidłowe dane uwierzytelniające organizacji"

#: ../server/rhnUser.py:610
#, python-format
msgid "User `%s' not a member of organization %s"
msgstr "Użytkownik „%s” nie jest członkiem organizacji %s"

#: ../server/rhnUser.py:638
#, python-format
msgid "username should be at least %d characters"
msgstr "nazwa użytkownika musi mieć co najmniej %d znaków"

#: ../server/rhnUser.py:641
#, python-format
msgid "username should be less than %d characters"
msgstr "nazwa użytkownika musi mieć mniej niż %d znaków"

#: ../server/rhnUser.py:652
#, python-format
msgid "username = `%s', invalid character `%s'"
msgstr "nazwa użytkownika to „%s”, nieprawidłowy znak „%s”"

#: ../server/rhnUser.py:670
#, python-format
msgid "Please limit your e-mail address to %s chars"
msgstr "Proszę ograniczyć adres e-mail do %s znaków"

#: ../server/rhnUser.py:743
#, python-format
msgid "password must be at least %d characters"
msgstr "hasło musi mieć co najmniej %d znaków"

#: ../server/rhnUser.py:746
#, python-format
msgid "Password must be shorter than %d characters"
msgstr "Hasło musi być krótsze niż %d znaków"

#: ../server/rhnUser.py:764
#, python-format
msgid "password contains character `%s'"
msgstr "hasło zawiera znak „%s”"

#: ../server/rhnUser.py:771
#, python-format
msgid "username should be at least %d characters long"
msgstr "nazwa użytkownika musi mieć co najmniej %d znaków"

#: ../server/rhnUser.py:782
#, python-format
msgid "Cannot register usernames ending with %s"
msgstr "Nie można rejestrować nazw użytkowników kończących się znakiem %s"

#: ../server/rhnChannel.py:1707
#, python-format
msgid ""
"Your account does not have access to any channels matching (release="
"'%(release)s', arch='%(arch)s')%(www_activation)s"
msgstr ""
"Konto nie ma dostępu do żadnych kanałów pasujących do (wydanie: "
"„%(release)s”, architektura: „%(arch)s”)%(www_activation)s"

#: ../server/rhnChannel.py:1717
msgid ""
"\n"
"If you have a registration number, please register with it first at http://"
"www.redhat.com/apps/activate/ and then try again.\n"
"\n"
msgstr ""
"\n"
"Numer rejestracji należy najpierw zarejestrować pod adresem http://www."
"redhat.com/apps/activate/ i spróbować ponownie.\n"
"\n"

#: ../server/rhnChannel.py:1727
#, python-format
msgid "Insufficient subscription permissions for release (%s, %s"
msgstr "Niewystarczające uprawnienia subskrypcji dla wydania (%s, %s"

#. Various messages that can be reused
#. 
#. bretm 02/07/2007 -- when we have better old-client documentation, probably
#. will be safe to get rid of all this crap
#: ../server/rhnChannel.py:1974 ../server/rhnChannel.py:1985
#: ../server/rhnChannel.py:2000 ../server/rhnChannel.py:2008
msgid "System Registered but Inactive"
msgstr "Zarejestrowano system, ale nie jest aktywny"

#: ../server/rhnChannel.py:1975
#, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates \n"
"because it is not subscribed to a channel. If you have not yet\n"
"activated your product for service, please visit our website at:\n"
"  \n"
"     http://www.redhat.com/apps/activate/\n"
"\n"
"...to activate your product."
msgstr ""
"\n"
"Nieprawidłowe połączenie architektury i wydania systemu operacyjnego (%s, "
"%s).\n"
"System został zarejestrowany , ale nie będzie otrzymywał aktualizacji,\n"
"ponieważ nie jest subskrybowany do kanału. Jeśli jeszcze nie\n"
"aktywowano produktu do usługi, należy odwiedzić naszą stronę na:\n"
"  \n"
"     http://www.redhat.com/apps/activate/\n"
"\n"
"…aby aktywować produkt."

#: ../server/rhnChannel.py:1986
#, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it could not be subscribed to a base channel.\n"
"Please contact your organization administrator for assistance.\n"
msgstr ""
"\n"
"Nieprawidłowe połączenie architektury i wydania systemu operacyjnego (%s, "
"%s).\n"
"System został zarejestrowany , ale nie będzie otrzymywał aktualizacji,\n"
"ponieważ nie jest subskrybowany do podstawowego kanału.\n"
"Proszę skontaktować się z administratorem organizacji po pomoc.\n"

#: ../server/rhnChannel.py:1993
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but is not yet entitled\n"
"  to service.  To entitle this system to service, login to the web site at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""
"\n"
"  Ten system został pomyślnie zarejestrowany, ale nie ma ważności\n"
"  do usługi. Aby uprawnić ten system do usługi, należy zalogować się na "
"stronie WWW pod adresem:\n"
"\n"
"  %(entitlement_url)s\n"

#: ../server/rhnChannel.py:2001
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but no service entitlements\n"
"  were available.  To entitle this system to service, login to the web site "
"at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""
"\n"
"  Ten system został pomyślnie zarejestrowany, ale żadne ważności\n"
"  nie były dostępne. Aby uprawnić ten system do usługi, należy zalogować się "
"na stronie WWW pod adresem:\n"
"\n"
"  %(entitlement_url)s\n"

#: ../server/rhnChannel.py:2009
msgid ""
"\n"
"  This system has been successfully registered, but the channel "
"subscriptions\n"
"  were exhausted\n"
msgstr ""
"\n"
"  Ten system został pomyślnie zarejestrowany, ale wyczerpano subskrypcje\n"
"  kanałów\n"

#: ../server/rhnHandler.py:61
msgid "Please run rhn_register as root on this client"
msgstr "Proszę wykonać polecenie rhn_register jako root na tym kliencie"

#: ../server/rhnHandler.py:78
#, python-format
msgid "Service not enabled for system profile: \"%s\""
msgstr "Usługa jest niedostępna dla profilu systemu: „%s”"

#: ../server/handlers/applet/applet.py:68
msgid "Your system was not found in the RHN database"
msgstr "Nie odnaleziono systemu w bazie danych usługi RHN"

#: ../server/handlers/sat/auth.py:45
msgid "ISS is disabled on this satellite."
msgstr "W tej usłudze Satellite wyłączono ISS."

#: ../server/handlers/sat/auth.py:57
#, python-format
msgid "Server \"%s\" is not enabled for ISS."
msgstr "Nie włączono serwera „%s” dla ISS."

#: ../server/handlers/xmlrpc/proxy.py:60
#, python-format
msgid "RHN Proxy service not enabled for server profile: \"%s\""
msgstr "Usługa RHN Proxy nie jest włączona dla profilu serwera: „%s”"

#: ../server/handlers/xmlrpc/proxy.py:80
msgid "Invalid session key"
msgstr "Nieprawidłowy klucz sesji"

#: ../server/handlers/xmlrpc/proxy.py:88
msgid "This server ID no longer exists"
msgstr "Ten identyfikator serwera już nie istnieje"

#: ../server/handlers/xmlrpc/registration.py:183
msgid "Required data missing"
msgstr "Brak wymaganych danych"

#: ../server/handlers/xmlrpc/registration.py:187
msgid "Required members missing"
msgstr "Brak wymaganych członków"

#: ../server/handlers/xmlrpc/registration.py:196
msgid "Attempt to register a system to an invalid username"
msgstr "Próba zarejestrowania systemu do nieprawidłowej nazwy użytkownika"

#: ../server/handlers/xmlrpc/registration.py:204
#, python-format
msgid ""
"\n"
"                   %s Account has been deactivated on this server.\n"
"                   Please contact your Org administrator for more help."
msgstr ""
"\n"
"                   Konto %s zostało dezaktywowane na tym serwerze.\n"
"                   Proszę skontaktować się z administratorem organizacji po "
"więcej pomocy."

#: ../server/handlers/xmlrpc/registration.py:819
msgid "Invalid system release version requested"
msgstr "Zażądano nieprawidłowej wersji wydania systemu"

#: ../server/handlers/xmlrpc/registration.py:1005
msgid "Red Hat Network Welcome Message"
msgstr "Komunikat powitalny usługi Red Hat Network"

#: ../server/handlers/xmlrpc/registration.py:1015
msgid "Red Hat Network Privacy Statement"
msgstr "Oświadczenie o prywatności usługi Red Hat Network"

#: ../server/handlers/xmlrpc/registration.py:1036
msgid "Expected a dictionary as a product argument"
msgstr "Oczekiwano słownika jako parametr produktu"

#: ../server/handlers/xmlrpc/registration.py:1068
#: ../server/handlers/xmlrpc/registration.py:1126
#, python-format
msgid "Not a valid Country: %s"
msgstr "Nie jest prawidłowym krajem: %s"

#: ../server/handlers/xmlrpc/registration.py:1349
#, python-format
msgid "Insufficient subscription permissions for release, arch (%s, %s)"
msgstr ""
"Niewystarczające uprawnienia subskrypcji dla wydania, architektury (%s, %s)"

#: ../server/handlers/xmlrpc/registration.py:1366
#, python-format
msgid "Invalid value '%s' for %s (%s)"
msgstr "Nieprawidłowa wartość „%s” dla %s (%s)"

#: ../server/handlers/xmlrpc/errata.py:59
#, python-format
msgid "Expected a package name, not: %s"
msgstr "Oczekiwano nazwy pakietu, nie: %s"

#: ../server/handlers/xmlrpc/errata.py:109
#, python-format
msgid "Expected a package, not: %s"
msgstr "Oczekiwano pakietu, nie: %s"

#: ../server/handlers/xmlrpc/queue.py:399
#, python-format
msgid "Invalid action value type %s (%s)"
msgstr "Nieprawidłowy typ wartości działania %s (%s)"

#: ../server/handlers/xmlrpc/queue.py:424
#, python-format
msgid "Action %s does not belong to server %s"
msgstr "Działanie %s nie należy do serwera %s"

#: ../server/handlers/xmlrpc/up2date.py:232
#, python-format
msgid "Invalid value %s (type %s)"
msgstr "Nieprawidłowa wartość %s (typ %s)"

#: ../server/handlers/xmlrpc/up2date.py:260
#, python-format
msgid "Unable to retrieve package header %s"
msgstr "Nie można pobrać nagłówka pakietu %s"

#: ../server/handlers/xmlrpc/up2date.py:407
#, python-format
msgid "Invalid value %s (%s)"
msgstr "Nieprawidłowa wartość %s (%s)"

#: ../server/handlers/xmlrpc/up2date.py:479
#, python-format
msgid "Invalid value for %s in package tuple: %s (%s)"
msgstr "Nieprawidłowa wartość dla %s w krotce pakietu: %s (%s)"

#: ../server/handlers/xmlrpc/up2date.py:491
#, python-format
msgid "Invalid package parameter %s (%s)"
msgstr "Nieprawidłowy parametr pakietu %s (%s)"

#: ../server/importlib/userAuth.py:108 ../server/importlib/userAuth.py:112
msgid "You are not authorized to manage packages in the null org"
msgstr "Brak upoważnienia do zarządzania pakietami w pustej organizacji"

#: ../server/importlib/userAuth.py:119
#, python-format
msgid "You are not allowed to manage packages in the %s org"
msgstr "Użytkownik nie może zarządzać pakietami w organizacji %s"

#: ../server/importlib/userAuth.py:137
msgid "You are not allowed to perform administrative tasks"
msgstr "Użytkownik nie może wykonywać zadań administracyjnych"

#: ../server/importlib/userAuth.py:164
#, python-format
msgid ""
"You are not allowed to manage channel %s, or that channel does not exist"
msgstr "Użytkownik nie może zarządzać kanałem %s lub ten kanał nie istnieje"

#: ../common/rhnTB.py:199
#, python-format
msgid "ERROR: %s %s: %s"
msgstr "BŁĄD: %s %s: %s"

#: ../common/rhnTB.py:201
#, python-format
msgid "TRACEBACK: %s"
msgstr "WYJĄTEK: %s"

#: ../common/rhnException.py:42
msgid "Outage mode"
msgstr "Serwer nie działa"

#. 0-999: RHN client/client-like interaction errors:
#: ../common/rhnException.py:44
msgid "This does not appear to be a valid username."
msgstr "To nie jest prawidłowa nazwa użytkownika."

#: ../common/rhnException.py:45
msgid "Invalid username and password combination."
msgstr "Nieprawidłowe połączenie nazwy użytkownika i hasła."

#: ../common/rhnException.py:46
msgid "This login is already taken, or the password is incorrect."
msgstr "Ten login jest zajęty lub hasło jest niepoprawne."

#: ../common/rhnException.py:47
msgid "Permission denied."
msgstr "Odmowa uprawnień."

#: ../common/rhnException.py:48
msgid "Can not create new entry."
msgstr "Nie można utworzyć nowego wpisu."

#: ../common/rhnException.py:49
msgid "Object not found."
msgstr "Nie odnaleziono obiektu."

#: ../common/rhnException.py:50
msgid "Account limits exceeded."
msgstr "Przekroczono ograniczenia konta."

#: ../common/rhnException.py:51
msgid "Invalid System Digital ID."
msgstr "Nieprawidłowy cyfrowy identyfikator systemu."

#: ../common/rhnException.py:52
msgid "Invalid System Credentials."
msgstr "Nieprawidłowe dane uwierzytelniające systemu."

#: ../common/rhnException.py:53
msgid "Could not retrieve user data from database."
msgstr "Nie można pobrać danych użytkownika z bazy danych."

#: ../common/rhnException.py:54
msgid "Valid username required."
msgstr "Wymagana jest prawidłowa nazwa użytkownika."

#: ../common/rhnException.py:55
msgid "Valid password required."
msgstr "Wymagane jest prawidłowe hasło."

#: ../common/rhnException.py:56
msgid "Minimum username length violation."
msgstr "Naruszono minimalną długość nazwy użytkownika."

#: ../common/rhnException.py:57
msgid "Minimum password length violation."
msgstr "Naruszono minimalną długość hasła."

#: ../common/rhnException.py:58
msgid "The username contains invalid characters."
msgstr "Nazwa użytkownika zawiera nieprawidłowe znaki."

#: ../common/rhnException.py:59
msgid "Invalid product registration code."
msgstr "Nieprawidłowy kod rejestracji produktu."

#: ../common/rhnException.py:60
msgid "File not found."
msgstr "Nie odnaleziono pliku."

#: ../common/rhnException.py:61
msgid "Invalid Architecture and OS release combination."
msgstr "Nieprawidłowe połączenie architektury i wydania systemu operacyjnego."

#: ../common/rhnException.py:62
msgid "Architecture and OS version combination is not supported."
msgstr "Nieobsługiwane połączenie architektury i wersji systemu operacyjnego."

#: ../common/rhnException.py:63
msgid "Could not retrieve system data from database."
msgstr "Nie można pobrać danych systemu z bazy danych."

#: ../common/rhnException.py:64
msgid "Invalid arguments passed to function."
msgstr "Do funkcji przekazano nieprawidłowe parametry."

#: ../common/rhnException.py:65
msgid "Unable to retrieve requested entry."
msgstr "Nie można pobrać żądanego wpisu."

#: ../common/rhnException.py:66
msgid "Could not update database entry."
msgstr "Nie można zaktualizować wpisu bazy danych."

#: ../common/rhnException.py:67
msgid "Unsupported server architecture."
msgstr "Nieobsługiwana architektura serwera."

#: ../common/rhnException.py:68
msgid "LDAP operation failed."
msgstr "Działanie LDAP się nie powiodło."

#: ../common/rhnException.py:69
msgid "Backend RPM database failure: can not retrieve requested information."
msgstr ""
"Niepowodzenie mechanizmu bazy danych RPM: nie można pobrać żądanych "
"informacji."

#: ../common/rhnException.py:71
msgid "Server Entry is busy."
msgstr "Wpis systemu jest zajęty."

#: ../common/rhnException.py:72
#, python-format
msgid ""
"\n"
"     The anonymous server functionality is no longer available.\n"
"\n"
"     Please re-register this system by running rhn_register\n"
"     as root.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable RHN service for this "
"system.\n"
"     "
msgstr ""
"\n"
"     Funkcja anonimowego serwera nie jest już dostępna.\n"
"\n"
"     Proszę ponownie zarejestrować ten system wykonując polecenie "
"rhn_register\n"
"     jako root.\n"
"     Proszę odwiedzić https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     lub zalogować się na https://%(hostname)s i z karty „Przegląd”\n"
"     wybrać „Zarządzanie subskrypcją”, aby włączyć usługę RHN dla tego "
"systemu.\n"
"     "

#: ../common/rhnException.py:81
msgid "Record not available in the database."
msgstr "Wpis jest niedostępny w bazie danych."

#: ../common/rhnException.py:82
msgid "Invalid value for entry."
msgstr "Nieprawidłowa wartość wpisu."

#: ../common/rhnException.py:83
#, python-format
msgid ""
"\n"
"     This system does not have a valid entitlement for Red Hat Network.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable RHN service for this "
"system.\n"
"     "
msgstr ""
"\n"
"     Ten system nie ma prawidłowej ważności dla usługi Red Hat Network.\n"
"     Proszę odwiedzić https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     lub zalogować się na https://%(hostname)s i z karty „Przegląd”\n"
"     wybrać „Zarządzanie subskrypcją”, aby włączyć usługę RHN dla tego "
"systemu.\n"
"     "

#: ../common/rhnException.py:89
msgid "Channel error"
msgstr "Błąd kanału"

#: ../common/rhnException.py:90
msgid "Client session token is invalid."
msgstr "Nieprawidłowy token sesji klienta."

#: ../common/rhnException.py:91
msgid "Client session token has expired."
msgstr "Token sesji klienta wygasł."

#: ../common/rhnException.py:92
msgid "You are not authorized to retrieve the requested object."
msgstr "Brak upoważnienia do pobierania żądanego obiektu."

#: ../common/rhnException.py:93
msgid "Invalid action"
msgstr "Nieprawidłowe działanie"

#: ../common/rhnException.py:94
msgid "You are not allowed to perform administrative tasks on this system."
msgstr "Użytkownik nie może wykonywać zadań administracyjnych w tym systemie."

#: ../common/rhnException.py:96
msgid "The system is already subscribed to the specified channel."
msgstr "Ten system już subskrybuje podany kanał."

#: ../common/rhnException.py:97
msgid "The system is not currently subscribed to the specified channel."
msgstr "Ten system obecnie nie subskrybuje podanego kanału."

#: ../common/rhnException.py:98
msgid "The specified channel does not exist."
msgstr "Podany kanał nie istnieje."

#: ../common/rhnException.py:99
msgid "Invalid channel version."
msgstr "Nieprawidłowa wersja kanału."

#: ../common/rhnException.py:100
msgid "Invalid ORG_ID requested"
msgstr "Zażądano nieprawidłowego identyfikatora organizacji"

#: ../common/rhnException.py:101
msgid ""
"\n"
"     User group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     user account. Please check with the organization administrator for your\n"
"     account if the maximum number of users allowed to subscribe to RHN "
"needs\n"
"     to be changed.\n"
"     "
msgstr ""
"\n"
"     Przekroczono ograniczenia członkostwa w grupach użytkowników.\n"
"\n"
"     Obecne ustawienia konta nie pozwalają na dodawanie kolejnego\n"
"     konta użytkownika. Proszę zapytać administratora organizacji o konto,\n"
"     jeśli maksymalna liczba użytkowników mogących subskrybować usługę RHN\n"
"     musi zostać zmieniona.\n"
"     "

#: ../common/rhnException.py:109
msgid ""
"\n"
"     System group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     system profile. Please check with the organization administrator for "
"your\n"
"     account for modifying the maximum number of system profiles that can be\n"
"     subscribed to your RHN account.\n"
"     "
msgstr ""
"\n"
"     Przekroczono ograniczenia członkostwa w grupach systemu.\n"
"\n"
"     Obecne ustawienia konta nie pozwalają na dodawanie kolejnego\n"
"     profilu systemu. Proszę zapytać administratora organizacji\n"
"     o zmodyfikowanie maksymalnej liczby profili systemów, jaka może\n"
"     subskrybować konto RHN.\n"
"     "

#: ../common/rhnException.py:117
msgid ""
"\n"
"     Invalid architecture.\n"
"\n"
"     The architecture of the package is not supported by Red Hat Network\n"
"     "
msgstr ""
"\n"
"     Nieprawidłowa architektura.\n"
"\n"
"     Architektura pakietu nie jest obsługiwana przez usługę Red Hat Network\n"
"     "

#: ../common/rhnException.py:122
msgid ""
"\n"
"     Incompatible architectures.\n"
"\n"
"     The architecture of the package you are trying to upload is not\n"
"     compatible with the channel architecture.\n"
"     "
msgstr ""
"\n"
"     Niezgodne architektury.\n"
"\n"
"     Architektura wysyłanego pakietu nie jest\n"
"     zgodna z architekturą kanału.\n"
"     "

#: ../common/rhnException.py:128
msgid "Invalid RPM header"
msgstr "Nieprawidłowy nagłówek pakietu RPM"

#: ../common/rhnException.py:129
msgid ""
"\n"
"     Invalid channel.\n"
"\n"
"     The channel you have specified does not exist.\n"
"     "
msgstr "\n"
"     Nieprawidłowy kanał.\n"
"\n"
"     Podany kanał nie istnieje.\n"
"     "

#: ../common/rhnException.py:134
#, python-format
msgid ""
"\n"
"     You are getting this error because RHN has detected an abuse of\n"
"     service from this system and account. This error is triggered when\n"
"     your system makes too many connections to Red Hat Network. This\n"
"     error can not be triggered under a normal use of the Red Hat Network\n"
"     service as configured by default on Red Hat Linux.\n"
"\n"
"     The Red Hat Network services for this system will remain disabled\n"
"     until you will reduce the RHN network traffic from your system to\n"
"     acceptable limits.\n"
"\n"
"     Please log into RHN and visit https://%(hostname)s/help/contact.pxt\n"
"     to contact technical support if you think you have received this\n"
"     message in error.\n"
"     "
msgstr ""
"\n"
"     Ten błąd występuje, ponieważ usługa RHN wykryła nadużycie\n"
"     usługi z tego systemu i konta. Ten błąd jest wywoływany, kiedy\n"
"     system tworzy za dużo połączeń z usługą Red Hat Network. Ten\n"
"     błąd nie może być wywoływany podczas normalnego używania usługi\n"
"     Red Hat Network skonfigurowanej domyślnie w systemie Red Hat Linux.\n"
"\n"
"     Usługi Red Hat Network dla tego systemu będą wyłączone,\n"
"     dopóki ruch sieci RHN z systemu nie zostanie zmniejszony do\n"
"     akceptowalnego poziomu.\n"
"\n"
"     Proszę zalogować się w usłudze RHN i odwiedzić https://%(hostname)s/"
"help/contact.pxt,\n"
"     aby skontaktować się ze wsparciem technicznym, jeśli ten komunikat\n"
"     nie powinien się pojawiać.\n"
"     "

#. For the uploading tools
#: ../common/rhnException.py:150
msgid "Invalid information uploaded to the server"
msgstr "Do serwera wysłano nieprawidłowe informacje"

#: ../common/rhnException.py:151
#, python-format
msgid ""
"\n"
"     Demo service currently disabled due to high load. If you would like\n"
"     to see Red Hat's policies on Demo service, or find out how you can\n"
"     purchase a subscription service and receive priority download access,\n"
"     please go to http://%(hostname)s/preview/index.pxt\n"
"     "
msgstr ""
"\n"
"     Usługa demonstracyjna jest obecnie wyłączona z powodu dużego\n"
"     obciążenia. Aby zobaczyć politykę firmy Red Hat w sprawie usługi\n"
"     demonstracyjnej lub dowiedzieć się, jak zakupić usługę subskrypcji\n"
"     i otrzymywać priorytetowy dostęp do pobierania, proszę odwiedzić\n"
"     stronę http://%(hostname)s/preview/index.pxt\n"
"     "

#: ../common/rhnException.py:157
#, python-format
msgid ""
"\n"
"     Access to Red Hat Network is currently limited to subscription "
"customers.\n"
"     Please try again later.  If you would like to become a subscription\n"
"     customer, go to https://%(hostname)s/preview/priority_service.pxt for\n"
"     more information.\n"
"     "
msgstr ""
"\n"
"     Dostęp do usługi Red Hat Network jest obecnie ograniczony dla klientów "
"subskrypcji.\n"
"     Proszę spróbować ponownie później. Aby zostać klientem subskrypcji,\n"
"     proszę przejść na stronę https://%(hostname)s/preview/priority_service."
"pxt\n"
"     po więcej informacji.\n"
"     "

#: ../common/rhnException.py:163
msgid "Error uploading network interfaces configuration."
msgstr "Błąd podczas wysyłania konfiguracji interfejsów sieciowych."

#: ../common/rhnException.py:164
msgid ""
"\n"
"     Package Upload Failed due to uniqueness constraint violation.\n"
"     Make sure the package does not have any duplicate dependencies or\n"
"     does not already exists on the server\n"
"     "
msgstr ""
"\n"
"     Wysłanie pakietu się nie powiodło z powodu naruszenia ograniczenia "
"unikalności.\n"
"     Proszę się upewnić, że pakiet nie ma podwójnych zależności lub\n"
"     nie istnieje już na serwerze\n"
"     "

#: ../common/rhnException.py:169
msgid ""
"\n"
"     The --force rhnpush option is disabled on this server. \n"
"     Please contact your Satellite administrator for more help.\n"
"     "
msgstr ""
"\n"
"     Na tym serwerze wyłączono opcję „--force rhnpush”. \n"
"     Proszę skontaktować się z administratorem usługi Satellite po więcej "
"pomocy.\n"
"     "

#. 60-70: token errors
#: ../common/rhnException.py:175
msgid ""
"\n"
"     The activation token specified could not be found on the server.\n"
"     Please retry with a valid key.\n"
"     "
msgstr ""
"\n"
"     Nie można odnaleźć podanego tokenu aktywacji na serwerze.\n"
"     Proszę spróbować ponownie za pomocą prawidłowego klucza.\n"
"     "

#: ../common/rhnException.py:179
msgid "Too many systems registered using this registration token"
msgstr "Za pomocą tego tokenu rejestracji zarejestrowano za dużo systemów"

#: ../common/rhnException.py:180
msgid "Token contains invalid, obsoleted or insufficient settings"
msgstr ""
"Token zawiera nieprawidłowe, przestarzałe lub niewystarczające ustawienia"

#: ../common/rhnException.py:181
msgid "Conflicting activation tokens"
msgstr "Sprzeczne tokeny aktywacji"

#. 70-80: channel subscription errors
#: ../common/rhnException.py:184
msgid ""
"\n"
"     All available subscriptions for the requested channel have been "
"exhausted.\n"
"     Please contact a Red Hat Network Sales associate.\n"
"     "
msgstr ""
"\n"
"     Wyczerpano wszystkie dostępne subskrypcje dla żądanego kanału.\n"
"     Proszę skontaktować się z przedstawicielem działu sprzedaży Red Hat "
"Network.\n"
"     "

#: ../common/rhnException.py:188
msgid ""
"\n"
"     You do not have subscription permission to the designated channel.\n"
"     Please refer to your organization's channel or organization\n"
"     administrators for further details.\n"
"     "
msgstr ""
"\n"
"     Nie ma uprawnienia subskrypcji dla wyznaczonego kanału.\n"
"     Kanał organizacji lub administratorzy organizacji mają więcej "
"informacji.\n"
"     "

#: ../common/rhnException.py:193
msgid "You can not unsubscribe from base channel."
msgstr "Nie można zrezygnować z subskrypcji podstawowego kanału."

#. 80-90: server group errors
#: ../common/rhnException.py:196
msgid "There was an error while trying to join the system to its groups"
msgstr "Wystąpił błąd podczas próby dołączenia systemu do jego grup"

#. 90-100: entitlement errors
#: ../common/rhnException.py:199
msgid "Unable to entitle system"
msgstr "Nie można upoważnić systemu"

#: ../common/rhnException.py:200
msgid ""
"Registration token unable to entitle system: maximum membership exceeded"
msgstr ""
"Token rejestracji nie może upoważnić systemu: przekroczono maksymalną liczbę "
"członkostw"

#. 100-109: e-mail and uuid related faults
#: ../common/rhnException.py:204
msgid "Maximum e-mail length violation."
msgstr "Naruszono maksymalną długość adresu e-mail."

#: ../common/rhnException.py:205
msgid "Changing e-mail address is not supported."
msgstr "Zmiana adresu e-mail nie jest obsługiwana."

#: ../common/rhnException.py:206
msgid "This system has been previously registered."
msgstr "Ten system został poprzednio zarejestrowany."

#: ../common/rhnException.py:207
msgid "Invalid username"
msgstr "Nieprawidłowa nazwa użytkownika"

#. 110-129: disabled org errors
#: ../common/rhnException.py:210
msgid "Service for your account has been disabled."
msgstr "Wyłączono usługę dla konta."

#: ../common/rhnException.py:211
msgid "Email address not validated; service disabled"
msgstr "Nie sprawdzono poprawności adresu e-mail. Wyłączono usługę"

#: ../common/rhnException.py:212
msgid "Survey not filled out; service disabled"
msgstr "Nie wypełniono ankiety. Wyłączono usługę"

#. 130-140: bugzilla errata import errors
#: ../common/rhnException.py:215
msgid "Bugzilla erratum import error"
msgstr "Błąd podczas importowania poprawki z Bugzilli"

#. 140-159 applet errors
#: ../common/rhnException.py:218
msgid "Unable to look up server"
msgstr "Nie można odnaleźć serwera"

#. 160-179: OSAD errors
#: ../common/rhnException.py:221
msgid "Required argument is missing"
msgstr "Brak wymaganego parametru"

#. 500-599: Package Uploader errors
#: ../common/rhnException.py:224
msgid "Missing HTTP header information"
msgstr "Brak informacji o nagłówku HTTP"

#: ../common/rhnException.py:225
msgid "The package's checksum signature does not match the header one"
msgstr "Podpis sumy kontrolnej pakietu nie zgadza się z podpisem w nagłówku"

#: ../common/rhnException.py:226
msgid "Header information does not match package metainformation"
msgstr "Informacje o nagłówku nie pasują do metainformacji pakietu"

#: ../common/rhnException.py:227
msgid "Package with a different signature already uploaded"
msgstr "Już wysłano pakiet o innym podpisie"

#: ../common/rhnException.py:228
msgid "Not an RPM package"
msgstr "Nie jest pakietem RPM"

#: ../common/rhnException.py:229
msgid "Unsigned RPM package"
msgstr "Niepodpisany pakiet RPM"

#: ../common/rhnException.py:230
msgid "Incompatible package and channel architectures"
msgstr "Niezgodne architektury pakietu i kanału"

#: ../common/rhnException.py:231
msgid "Incompatible checksum type"
msgstr "Niezgodny typ sumy kontrolnej"

#. 600-699: RHEL5+ EN errors
#: ../common/rhnException.py:234
msgid "Invalid Entitlement Number"
msgstr "Nieprawidłowy numer ważności"

#: ../common/rhnException.py:235
msgid "No entitlement information tied to hardware"
msgstr "Brak informacji o ważności powiązanych z tym sprzętem"

#: ../common/rhnException.py:236
msgid "Installation number is not entitling"
msgstr "Numer instalacji nie jest ważny"

#. 700-799: Additional user input verification errors.
#: ../common/rhnException.py:239
msgid "Maximum username length violation"
msgstr "Naruszono maksymalną długość nazwy użytkownika"

#: ../common/rhnException.py:240
msgid "Maximum password length violation"
msgstr "Naruszono maksymalną długość hasła"

#: ../common/rhnException.py:242
msgid "System Name cannot be less than 3 characters"
msgstr "Nazwa systemu nie może być krótsza niż 3 znaki"

#. 1000-1999: RHN Proxy specific errors:
#. issued by an RHN Proxy to the client
#: ../common/rhnException.py:246
msgid "RHN Proxy error."
msgstr "Błąd usługi RHN Proxy."

#: ../common/rhnException.py:247
msgid "RHN Proxy unable to login."
msgstr "Nie można zalogować usługi RHN Proxy."

#. issued by an RHN Server/Satellite to the proxy
#: ../common/rhnException.py:249
msgid ""
"\n"
"     RHN Proxy system ID does not match an RHN Proxy Server\n"
"     in the database. Please contact your designated Red Hat representative\n"
"     or visit https://rhn.redhat.com/help/contact.pxt immediately if\n"
"     experiencing difficulties with the process of enabling or continued\n"
"     enablement of this RHN Proxy Server.\n"
"     "
msgstr ""
"\n"
"     Identyfikator systemu usługi RHN Proxy nie pasuje do serwera RHN Proxy\n"
"     w bazie danych. Proszę skontaktować się z wyznaczonym przedstawicielem "
"firmy Red Hat\n"
"     lub odwiedzić stronę https://rhn.redhat.com/help/contact.pxt, jeśli\n"
"     występują problemy z procesem włączania lub kontynuowanego\n"
"     włączania tego serwera RHN Proxy.\n"
"     "

#: ../common/rhnException.py:256
msgid "RHN Proxy session token is invalid."
msgstr "Token sesji usługi RHN Proxy jest nieprawidłowy."

#: ../common/rhnException.py:257
msgid "RHN Proxy session token has expired."
msgstr "Token sesji usługi RHN Proxy wygasł."

#. 2000-2999: RHN Satellite specific errors:
#: ../common/rhnException.py:261
msgid ""
"\n"
"     RHN Satellite user creation is not allowed via rhn_register;\n"
"     please contact your sysadmin to have your account created.\n"
"     "
msgstr ""
"\n"
"     Tworzenie użytkownika usługi RHN Satellite za pomocą polecenia "
"rhn_register nie jest dozwolone.\n"
"     Proszę skontaktować się z administratorem systemu w celu utworzenia "
"konta.\n"
"     "

#: ../common/rhnException.py:265
msgid ""
"\n"
"     RHN Satellite system ID does not match an RHN Satellite Server\n"
"     in the database. Please contact your designated Red Hat representative\n"
"     or visit https://rhn.redhat.com/help/contact.pxt immediately if\n"
"     experiencing difficulties with the process of enabling or continued\n"
"     enablement of this RHN Satellite Server.\n"
"     "
msgstr ""
"\n"
"     Identyfikator systemu usługi RHN Satellite nie pasuje do serwera RHN "
"Satellite\n"
"     w bazie danych. Proszę skontaktować się z wyznaczonym przedstawicielem "
"firmy Red Hat\n"
"     lub odwiedzić stronę https://rhn.redhat.com/help/contact.pxt, jeśli\n"
"     występują problemy z procesem włączania lub kontynuowanego\n"
"     włączania tego serwera RHN Satellite.\n"
"     "

#: ../common/rhnException.py:272
msgid ""
"\n"
"     This satellite server is not allowed to access the specified channel\n"
"     "
msgstr ""
"\n"
"     Ten serwer usługi Satellite nie ma dostępu do podanego kanału\n"
"     "

#: ../common/rhnException.py:275
msgid ""
"\n"
"     This satellite server is not allowed to use Inter Satellite Sync on "
"this satellite\n"
"     "
msgstr ""
"\n"
"     Ten serwer usługi Satellite ne może używać Inter Satellite Sync na tej "
"usłudze Satellite\n"
"     "

#: ../common/rhnException.py:278
msgid "\n"
"     Inter Satellite Sync is disabled on this satellite.\n"
"     "
msgstr ""
"\n"
"     Inter Satellite Sync jest wyłączone na tej usłudze Satellite.\n"
"     "

#. Kickstart errors
#: ../common/rhnException.py:283
msgid "Access denied to kickstart tree"
msgstr "Odmowa dostępu do drzewa kickstart"

#: ../common/rhnException.py:284
msgid "Could not find kickstart file"
msgstr "Nie można odnaleźć pliku kickstart"

#: ../common/rhnException.py:285
msgid ""
"\n"
"     Kickstart tree would not lint, there are packages\n"
"     missing in the channel\n"
"     "
msgstr ""
"\n"
"     Nie można oczyścić drzewa kickstart, brakuje pakietów\n"
"     w kanale\n"
"     "

#. 3000-3999: XML dumper errors:
#: ../common/rhnException.py:291
msgid "Invalid datatype passed"
msgstr "Przekazano nieprawidłowy typ danych"

#: ../common/rhnException.py:292
msgid "Unable to retrieve channel"
msgstr "Nie można pobrać kanału"

#: ../common/rhnException.py:293
msgid "Invalid package name"
msgstr "Nieprawidłowa nazwa pakietu"

#: ../common/rhnException.py:294
msgid "Unable to retrieve package"
msgstr "Nie można pobrać pakietu"

#: ../common/rhnException.py:295
msgid "Invalid erratum name"
msgstr "Nieprawidłowa nazwa poprawki"

#: ../common/rhnException.py:296
msgid "Unable to retrieve erratum"
msgstr "Nie można pobrać poprawki"

#: ../common/rhnException.py:297
msgid "Invalid satellite certificate"
msgstr "Nieprawidłowy certyfikat usługi Satellite"

#: ../common/rhnException.py:298
msgid "File is missing"
msgstr "Brak pliku"

#: ../common/rhnException.py:299
msgid "Function retrieval error"
msgstr "Błąd pobierania funkcji"

#: ../common/rhnException.py:300
msgid "Function execution error"
msgstr "Błąd wykonywania funkcji"

#: ../common/rhnException.py:301
msgid "Missing version string"
msgstr "Brak ciągu wersji"

#: ../common/rhnException.py:302
msgid "Invalid version string"
msgstr "Nieprawidłowy ciąg wersji"

#: ../common/rhnException.py:303
msgid "Mismatching versions"
msgstr "Niepasujące wersje"

#: ../common/rhnException.py:304
msgid "Invalid channel version"
msgstr "Nieprawidłowa wersja kanału"

#: ../common/rhnException.py:305
msgid "Missing snapshot for channels"
msgstr "Brak migawki dla kanałów"

#: ../common/rhnException.py:306
msgid "No comps file for channel"
msgstr "Brak pliku comps dla kanału"

#: ../common/rhnException.py:307
msgid "Unable to retrieve comps file"
msgstr "Nie można pobrać pliku comps"

#. 4000 - 4999: config management errors
#: ../common/rhnException.py:310
msgid "Configuration action missing"
msgstr "Brak działania konfiguracji"

#: ../common/rhnException.py:311
msgid "File too large"
msgstr "Plik jest za duży"

#: ../common/rhnException.py:312
msgid "File contains binary data"
msgstr "Plik zawiera binarne dane"

#: ../common/rhnException.py:313
msgid "Configuration channel is not empty"
msgstr "Kanał konfiguracji nie jest pusty"

#: ../common/rhnException.py:314
msgid "Permission error"
msgstr "Błąd uprawnień"

#: ../common/rhnException.py:315
msgid "Content missing for configuration file"
msgstr "Brak treści pliku konfiguracji"

#: ../common/rhnException.py:316
msgid "Template delimiters not specified"
msgstr "Nie podano separatorów szablonu"

#: ../common/rhnException.py:317
msgid "Configuration channel does not exist"
msgstr "Kanał konfiguracji nie istnieje"

#: ../common/rhnException.py:318
msgid "Configuration channel already exists"
msgstr "Kanał konfiguracji już istnieje"

#: ../common/rhnException.py:319
msgid "File missing from configuration channel"
msgstr "Brak pliku z kanału konfiguracji"

#: ../common/rhnException.py:320
msgid "Different revision of this file is uploaded"
msgstr "Inna wersja tego pliku została wysłana"

#: ../common/rhnException.py:321
msgid "File already uploaded to configuration channel"
msgstr "Już wysłano plik do kanału konfiguracji"

#: ../common/rhnException.py:322
msgid "File size exceeds remaining quota space"
msgstr "Rozmiar pliku przekracza pozostałe miejsce przydziału"

#: ../common/rhnException.py:323
msgid "Full path of file must be specified"
msgstr "Należy podać pełną ścieżkę do pliku"

#: ../common/rhnException.py:324
msgid "Invalid revision number"
msgstr "Nieprawidłowy numer wersji"

#: ../common/rhnException.py:325
msgid "Cannot compare files of different file type"
msgstr "Nie można porównywać plików różnego typu"

#. 5000 - 5099: entitlement mapper errors
#: ../common/rhnException.py:328
msgid "The speicified item is not present in the input"
msgstr "Podany element nie jest obecny w wejściu"

#: ../common/rhnException.py:329
msgid "Invalid item code"
msgstr "Nieprawidłowy kod elementu"

#: ../common/rhnException.py:330
msgid "Invalid user role"
msgstr "Nieprawidłowa rola użytkownika"

#: ../common/rhnException.py:331
msgid "Invalid server group"
msgstr "Nieprawidłowa grupa serwera"

#: ../common/rhnException.py:332
msgid "Invalid channel family"
msgstr "Nieprawidłowa rodzina kanału"

#: ../common/rhnException.py:376
msgid ""
"\n"
"     An error has occurred while processing your request. If this problem\n"
"     persists please enter a bug report at bugzilla.redhat.com.\n"
"     If you choose to submit the bug report, please be sure to include\n"
"     details of what you were trying to do when this error occurred and\n"
"     details on how to reproduce this problem.\n"
msgstr ""
"\n"
"     Wystąpił błąd podczas przetwarzania żądania. Jeśli problem\n"
"     się powtarza, proszę zgłosić błąd na stronie bugzilla.redhat.com.\n"
"     Jeśli błąd zostanie zgłoszony, to proszę dołączyć informacje\n"
"     o próbowanym działaniu, kiedy wystąpił błąd i informacje o sposobie\n"
"     powtórzenia tego problemu.\n"

#: ../common/rhnException.py:430
#, python-format
msgid "Error Message:\n"
"    %s\n"
msgstr "Komunikat o błędzie:\n"
"    %s\n"

#: ../common/rhnException.py:432
#, python-format
msgid "Error Class Code: %s\n"
msgstr "Kod klasy błędu: %s\n"

#: ../common/rhnException.py:435
#, python-format
msgid "Error Class Info: %s\n"
msgstr "Informacje o klasie błędu: %s\n"

#: ../common/rhnException.py:437
#, python-format
msgid "Explanation: %s"
msgstr "Wyjaśnienie: %s"
